### YamlMime:ManagedReference
items:
- uid: ProjectePorres.Data.ConfigContext
  commentId: T:ProjectePorres.Data.ConfigContext
  id: ConfigContext
  parent: ProjectePorres.Data
  children:
  - ProjectePorres.Data.ConfigContext.#ctor(System.String)
  - ProjectePorres.Data.ConfigContext.Config
  - ProjectePorres.Data.ConfigContext.EscriureConfiguracio(System.String,System.String,System.String)
  - ProjectePorres.Data.ConfigContext.LlegirConfiguracio
  - ProjectePorres.Data.ConfigContext.RetornarValor(System.String,System.String)
  - ProjectePorres.Data.ConfigContext.RutaArxiu
  langs:
  - csharp
  - vb
  name: ConfigContext
  nameWithType: ConfigContext
  fullName: ProjectePorres.Data.ConfigContext
  type: Class
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: ConfigContext
    path: Data/ConfigContext.cs
    startLine: 8
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public class ConfigContext
    content.vb: Public Class ConfigContext
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: ProjectePorres.Data.ConfigContext.Config
  commentId: P:ProjectePorres.Data.ConfigContext.Config
  id: Config
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: ConfigContext.Config
  fullName: ProjectePorres.Data.ConfigContext.Config
  type: Property
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: Config
    path: Data/ConfigContext.cs
    startLine: 14
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public IniData Config { get; set; }
    parameters: []
    return:
      type: IniParser.Model.IniData
    content.vb: Public Property Config As IniData
  overload: ProjectePorres.Data.ConfigContext.Config*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: ProjectePorres.Data.ConfigContext.RutaArxiu
  commentId: P:ProjectePorres.Data.ConfigContext.RutaArxiu
  id: RutaArxiu
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: RutaArxiu
  nameWithType: ConfigContext.RutaArxiu
  fullName: ProjectePorres.Data.ConfigContext.RutaArxiu
  type: Property
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: RutaArxiu
    path: Data/ConfigContext.cs
    startLine: 15
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public string RutaArxiu { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property RutaArxiu As String
  overload: ProjectePorres.Data.ConfigContext.RutaArxiu*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: ProjectePorres.Data.ConfigContext.#ctor(System.String)
  commentId: M:ProjectePorres.Data.ConfigContext.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: ConfigContext(String)
  nameWithType: ConfigContext.ConfigContext(String)
  fullName: ProjectePorres.Data.ConfigContext.ConfigContext(System.String)
  type: Constructor
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: .ctor
    path: Data/ConfigContext.cs
    startLine: 18
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public ConfigContext(string rutaArxiu)
    parameters:
    - id: rutaArxiu
      type: System.String
    content.vb: Public Sub New(rutaArxiu As String)
  overload: ProjectePorres.Data.ConfigContext.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: ProjectePorres.Data.ConfigContext.LlegirConfiguracio
  commentId: M:ProjectePorres.Data.ConfigContext.LlegirConfiguracio
  id: LlegirConfiguracio
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: LlegirConfiguracio()
  nameWithType: ConfigContext.LlegirConfiguracio()
  fullName: ProjectePorres.Data.ConfigContext.LlegirConfiguracio()
  type: Method
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: LlegirConfiguracio
    path: Data/ConfigContext.cs
    startLine: 31
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public void LlegirConfiguracio()
    content.vb: Public Sub LlegirConfiguracio
  overload: ProjectePorres.Data.ConfigContext.LlegirConfiguracio*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: ProjectePorres.Data.ConfigContext.EscriureConfiguracio(System.String,System.String,System.String)
  commentId: M:ProjectePorres.Data.ConfigContext.EscriureConfiguracio(System.String,System.String,System.String)
  id: EscriureConfiguracio(System.String,System.String,System.String)
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: EscriureConfiguracio(String, String, String)
  nameWithType: ConfigContext.EscriureConfiguracio(String, String, String)
  fullName: ProjectePorres.Data.ConfigContext.EscriureConfiguracio(System.String, System.String, System.String)
  type: Method
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: EscriureConfiguracio
    path: Data/ConfigContext.cs
    startLine: 34
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public void EscriureConfiguracio(string clau, string camp, string nouValor)
    parameters:
    - id: clau
      type: System.String
    - id: camp
      type: System.String
    - id: nouValor
      type: System.String
    content.vb: Public Sub EscriureConfiguracio(clau As String, camp As String, nouValor As String)
  overload: ProjectePorres.Data.ConfigContext.EscriureConfiguracio*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: ProjectePorres.Data.ConfigContext.RetornarValor(System.String,System.String)
  commentId: M:ProjectePorres.Data.ConfigContext.RetornarValor(System.String,System.String)
  id: RetornarValor(System.String,System.String)
  parent: ProjectePorres.Data.ConfigContext
  langs:
  - csharp
  - vb
  name: RetornarValor(String, String)
  nameWithType: ConfigContext.RetornarValor(String, String)
  fullName: ProjectePorres.Data.ConfigContext.RetornarValor(System.String, System.String)
  type: Method
  source:
    remote:
      path: ProjectePorres/Data/ConfigContext.cs
      branch: docfx
      repo: https://github.com/caiocesar-ins-montilivi/PorresApp.git
    id: RetornarValor
    path: Data/ConfigContext.cs
    startLine: 41
  assemblies:
  - ProjectePorres
  namespace: ProjectePorres.Data
  syntax:
    content: public string RetornarValor(string clau, string camp)
    parameters:
    - id: clau
      type: System.String
    - id: camp
      type: System.String
    return:
      type: System.String
    content.vb: Public Function RetornarValor(clau As String, camp As String) As String
  overload: ProjectePorres.Data.ConfigContext.RetornarValor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: ProjectePorres.Data
  commentId: N:ProjectePorres.Data
  name: ProjectePorres.Data
  nameWithType: ProjectePorres.Data
  fullName: ProjectePorres.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: ProjectePorres.Data.ConfigContext.Config*
  commentId: Overload:ProjectePorres.Data.ConfigContext.Config
  name: Config
  nameWithType: ConfigContext.Config
  fullName: ProjectePorres.Data.ConfigContext.Config
- uid: IniParser.Model.IniData
  commentId: T:IniParser.Model.IniData
  parent: IniParser.Model
  isExternal: true
  name: IniData
  nameWithType: IniData
  fullName: IniParser.Model.IniData
- uid: IniParser.Model
  commentId: N:IniParser.Model
  isExternal: true
  name: IniParser.Model
  nameWithType: IniParser.Model
  fullName: IniParser.Model
- uid: ProjectePorres.Data.ConfigContext.RutaArxiu*
  commentId: Overload:ProjectePorres.Data.ConfigContext.RutaArxiu
  name: RutaArxiu
  nameWithType: ConfigContext.RutaArxiu
  fullName: ProjectePorres.Data.ConfigContext.RutaArxiu
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: ProjectePorres.Data.ConfigContext.#ctor*
  commentId: Overload:ProjectePorres.Data.ConfigContext.#ctor
  name: ConfigContext
  nameWithType: ConfigContext.ConfigContext
  fullName: ProjectePorres.Data.ConfigContext.ConfigContext
- uid: ProjectePorres.Data.ConfigContext.LlegirConfiguracio*
  commentId: Overload:ProjectePorres.Data.ConfigContext.LlegirConfiguracio
  name: LlegirConfiguracio
  nameWithType: ConfigContext.LlegirConfiguracio
  fullName: ProjectePorres.Data.ConfigContext.LlegirConfiguracio
- uid: ProjectePorres.Data.ConfigContext.EscriureConfiguracio*
  commentId: Overload:ProjectePorres.Data.ConfigContext.EscriureConfiguracio
  name: EscriureConfiguracio
  nameWithType: ConfigContext.EscriureConfiguracio
  fullName: ProjectePorres.Data.ConfigContext.EscriureConfiguracio
- uid: ProjectePorres.Data.ConfigContext.RetornarValor*
  commentId: Overload:ProjectePorres.Data.ConfigContext.RetornarValor
  name: RetornarValor
  nameWithType: ConfigContext.RetornarValor
  fullName: ProjectePorres.Data.ConfigContext.RetornarValor
